local wezterm = require 'wezterm';

return {
	force_reverse_video_cursor = true,
	color_scheme = "nord",
	font = wezterm.font({ family = "SFMono Nerd Font", weight = "Light", harfbuzz_features = { "calt=0", "clig=0", "liga=0" } }),
	font_size = 15,
	font_rules = {
		{
			intensity = "Bold",
			font = wezterm.font({ family = "SFMono Nerd Font", weight = "Bold", harfbuzz_features = { "calt=0", "clig=0", "liga=0" } }),
		},
	},
	window_close_confirmation = "NeverPrompt",
	hide_tab_bar_if_only_one_tab = true,
	leader = { key = "a", mods = "CTRL", timeout_milliseconds = 1000 },
	keys = {
		{ key = "F", mods = "SHIFT|CMD", action = "ToggleFullScreen" },
		{ key = "T", mods = "SHIFT|CMD", action = wezterm.action { SpawnTab = "CurrentPaneDomain" } },
		{ key = "H", mods = "SHIFT|CMD", action = wezterm.action { SplitHorizontal = { domain = "CurrentPaneDomain" } } },
		{ key = "V", mods = "SHIFT|CMD", action = wezterm.action { SplitVertical = { domain = "CurrentPaneDomain" } } },
		{ key = "h", mods = "LEADER",    action = wezterm.action { AdjustPaneSize = { "Left", 5 } } },
		{ key = "j", mods = "LEADER",    action = wezterm.action { AdjustPaneSize = { "Down", 5 } } },
		{ key = "k", mods = "LEADER",    action = wezterm.action { AdjustPaneSize = { "Up", 5 } } },
		{ key = "l", mods = "LEADER",    action = wezterm.action { AdjustPaneSize = { "Right", 5 } } },
		{ key = "H", mods = "SHIFT|ALT", action = wezterm.action { ActivatePaneDirection = "Left" } },
		{ key = "L", mods = "SHIFT|ALT", action = wezterm.action { ActivatePaneDirection = "Right" } },
		{ key = "K", mods = "SHIFT|ALT", action = wezterm.action { ActivatePaneDirection = "Up" } },
		{ key = "J", mods = "SHIFT|ALT", action = wezterm.action { ActivatePaneDirection = "Down" } },
		{ key = 'h', mods = 'ALT',       action = wezterm.action { ActivateTabRelative = -1 } },
		{ key = 'l', mods = 'ALT',       action = wezterm.action { ActivateTabRelative = 1 } },
		{ key = 'j', mods = 'ALT',       action = wezterm.action { MoveTabRelative = -1 } },
		{ key = 'k', mods = 'ALT',       action = wezterm.action { MoveTabRelative = 1 } },
	},
	enable_tab_bar = false,
	window_decorations = "RESIZE",
	window_padding = {
		left = 0,
		right = 0,
		top = 0,
		bottom = 0,
	},
	initial_rows = 40,
	initial_cols = 150,
	-- native_macos_fullscreen_mode = true,
	exit_behavior = "Close",
	hide_mouse_cursor_when_typing = true,
	max_fps = 60,
}
