# Font configuration (adjust to your preferred monospace font)
font_family      family="GoogleSansM Nerd Font"
font_size        11.0

# Cursor Configuration
cursor_shape block
cursor_shape_unfocused hollow
cursor_trail 0
shell_integration no-cursor

# UI & Padding (Mimicking Alacritty's clean viewport)
window_padding_width 2
hide_window_decorations yes

# Graphics & Rendering Performance (Graphics protocol is enabled natively)
repaint_delay    8
input_delay      3
sync_to_monitor  yes

# Hide Tab Bar completely
tab_bar_style    hidden

# Strip Out Multiplexing Shortcuts
map ctrl+shift+enter no_op
map ctrl+shift+n     no_op
map ctrl+shift+w     no_op
map ctrl+shift+]     no_op
map ctrl+shift+[     no_op
map ctrl+shift+t     no_op
map ctrl+shift+q     no_op
map ctrl+shift+t     launch --cwd=current --type=os-window
map ctrl+shift+space show_scrollback

# Nord Color Scheme

# Basic Colors
foreground            #d8dee9
background            #2e3440
selection_foreground  #000000
selection_background  #eceff4

# Cursor
cursor                #d8dee9
cursor_text_color     #2e3440

# URL color
url_color             #88c0d0

# Window border colors
active_border_color   #4c566a
inactive_border_color #2e3440

# Tab bar colors (if enabled)
active_tab_foreground   #2e3440
active_tab_background   #eceff4
inactive_tab_foreground #e5e9f0
inactive_tab_background #434c5e

# Normal colors
color0 #3b4252
color1 #bf616a
color2 #a3be8c
color3 #ebcb8b
color4 #81a1c1
color5 #b48ead
color6 #88c0d0
color7 #e5e9f0

# Bright colors
color8  #4c566a
color9  #bf616a
color10 #a3be8c
color11 #ebcb8b
color12 #81a1c1
color13 #b48ead
color14 #8fbcbb
color15 #eceff4
