# ~/.config/hypr/hypridle.conf
# 1. Dim the screen after 2.5 minutes of inactivity
listener {
    timeout = 150                                     
    on-timeout = brightnessctl -d intel_backlight -s set 10%         # Save current brightness, then dim to 10%
    on-resume = brightnessctl -d intel_backlight -r                  # Restore original brightness
}
# 2. Lock the screen after 5 minutes
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# 3. Turn off the monitors after 5.5 minutes
#listener {
#    timeout = 330                                 
#    on-timeout = hyprctl dispatch dpms off        
#    on-resume = hyprctl dispatch dpms on          
#}

listener {
    timeout = 330
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# 4. Suspend the computer entirely after 30 minutes
listener {
    timeout = 1800                                
    on-timeout = systemctl suspend                
}

#general {
    #lock_cmd = pidof hyprlock || hyprlock
    #before_sleep_cmd = loginctl lock-session
    #after_sleep_cmd = hyprctl dispatch dpms on
#}

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}
